config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'airports#index'
  resources :airports
  post 'airports/new', to: 'airports#create'
end

app/models/airport.rb
class Airport < ApplicationRecord
    has_many :users, through: :user_airports
    has_many :user_airports

    # validates :code, presence: true
    validates_presence_of :code, :message => "can't be empty"
    validates_uniqueness_of :code, :case_sensitive => false
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
    has_many :airports, through: :user_airports
    has_many :user_airports
end

app/models/user_airport.rb
class UserAirport < ApplicationRecord
    belongs_to :user
    belongs_to :airport 
end

app/controllers/airports_controller.rb
require 'net/http'
require 'json'
require 'tzinfo'

class AirportsController < ApplicationController

    def index
        @airports = Airport.all
    end

    def show
    end

    def new
        @airport = Airport.new
    end
    
    def create
      respond_to do |format|
        response = Net::HTTP.get_response('api.weather.gov', '/stations/K' + airport_params[:code] + '/observations/latest')
        loc = response.header['location']
        if (response.code == "301")
          response = Net::HTTP.get_response(URI.parse(loc))
        end
        if (response.code=="200")
          # airport was found by weather.gov api
          # the first condition is that something was returned at all (code=="200")
          # the second condition is that the response must contain the word county because otherwise the airport was not found          
          parsed_response = JSON.parse(response.body)
          airport_url = parsed_response["properties"]["station"]
          airport_data = JSON.parse(Net::HTTP.get_response(URI.parse(airport_url)).body)
          airport_name = airport_data["properties"]["name"]
          timezone_name = airport_data["properties"]["timeZone"]
          weather_desc = parsed_response["properties"]["textDescription"]
          weather_celsius = parsed_response["properties"]["temperature"]["value"]
          weather_icon = parsed_response["properties"]["icon"]

          #TODO Use timezone name and gem 'tzinfo' to display time in local time
          # tz = TZInfo::Timezone.get(timezone_name)
          @airport = Airport.new(airport_params)

          @airport.name = airport_name
          @airport.timezone = timezone_name
          @airport.desc = weather_desc
          @airport.celsius = weather_celsius
          @airport.icon = weather_icon

          if @airport.save
            format.html { redirect_to airports_path, notice: 'Airport was successfully added.' }
            format.json { render :show, status: :created, location: @airport }
          else
            format.html { render :new }
            format.json { render json: @airport.errors, status: :unprocessable_entity }
          end
        else
          format.html { redirect_to airports_path, notice: 'Airport was not found.' }
          format.json { render json: @airport.errors, status: :unprocessable_entity }
        end
      end
    end
    
    def destroy
      set_airport
      @airport.destroy
      respond_to do |format|
        format.html { redirect_to airports_url, notice: 'Airport was successfully removed.' }
        format.json { head :no_content }
      end
    end

    def update
      set_airport
      response = Net::HTTP.get_response('api.weather.gov', '/stations/K' + @airport.code + '/observations/latest')
      loc = response.header['location']
      if (response.code == "301")
        response = Net::HTTP.get_response(URI.parse(loc))
      end
      if (response.code=="200")
        # airport was found by weather.gov api
        # the first condition is that something was returned at all (code=="200")
        # the second condition is that the response must contain the word county because otherwise the airport was not found          
        parsed_response = JSON.parse(response.body)
        weather_desc = parsed_response["properties"]["textDescription"]
        weather_celsius = parsed_response["properties"]["temperature"]["value"]
        weather_icon = parsed_response["properties"]["icon"]
      end
      @airport.update(desc: weather_desc, celsius: weather_celsius, icon: weather_icon)
      redirect_to airports_url
    end
    
    private
    # Use callbacks to share common setup or constraints between actions.
    def set_airport
      @airport = Airport.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def airport_params
      params.require(:airport).permit(:code)
    end


    
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/airports_helper.rb
module AirportsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/airports/_form.html.erb
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

<%= form_with(model: airport, local: true) do |form| %>

    <% if @airport.errors.any? %>
    <div id="error_explanation my-3">
        <h5><%= pluralize(@airport.errors.count, "error") %> prohibited this article from being saved:</h2>
 
        <ul style="display: inline-block">
        <% @airport.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
        </ul>
    </div>
    <% end %>

    <div class="field my-3">
        <%= form.label :code %>
        <%= form.text_field :code %>
    </div>

    <div class="actions my-3">
    <%= form.submit %>
    </div>
<% end%>

app/views/airports/index.html.erb
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

<% require 'tzinfo' %>

<!-- Header -->
<header class="masthead d-flex">
  <div class="container text-center my-auto">
    <br>
    <h1 class="mb-1">Amazing Airport App</h1>
    <h3 class="mb-5">
      <small><em>developed with ♡ by Alex Chen and Rina Kawamura</em></small>
    </h3>
  </div>
  <div class="overlay"></div>
</header>

<!-- Table -->
  <section class="content-section bg-light" id="table">
    <div class="container text-center">
      <div class="row">
        <div class="col-lg-10 mx-auto my-3">
          <table>
            <col width="100">
            <col width="100">
            <col width="100">
            <thead>
              <tr>
                <th>Airport Code</th>
                <th>Airport Name</th>
                <th>Local Time</th>
                <th>Weather</th>
                <th>Temperature (°C)</th>
                <th>Icon</th>
        
                <th colspan="3"></th>
              </tr>
            </thead>
        
            <tbody>
              <% @airports.each do |airport| %>
                <tr>
                  <td><%= airport.code.upcase %></td>
                  <td><%= airport.name %></td>
                  <td><%= TZInfo::Timezone.get(airport.timezone).utc_to_local(Time.now.utc) %></td>
                  <td><%= airport.desc %></td>
                  <td><%= ((airport.celsius.to_f) * 1000).floor / 1000.0 %></td>
                  <% if airport.icon %>
                    <td class="img-rounded"><%= image_tag(airport.icon, :alt => "airport weather icon", :class => "rounded-circle") %></td>
                  <% end %>
        
                  <td><%= button_to 'Refresh Data', airport,{method: :patch, class: 'btn'} %></td>
                  <td><%= button_to 'Destroy', airport, {method: :delete, class: 'btn btn-primary', data: { confirm: 'Are you sure?' }} %></td>
                </tr>
              <% end %>
            </tbody>
          </table>




          
        </div>
      </div>
    </div>
  </section>

  <!-- Add Airport -->
  <section class="content-section" id="add">
    <div class="container text-center">
      <div class="row">
        <div class="col mx-auto my-3">
          <p id="notice"><%= notice %></p>
          <%= link_to 'Add Airport', new_airport_path %>
          </div>
      </div>
    </div>
  </section>

app/views/airports/new.html.erb
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

<!-- Header -->
<header class="masthead d-flex">
  <div class="container text-center my-auto">
    <br>
    <h1 class="mb-1">Add Airport</h1>
    <h3 class="mb-5">
      <small><em>Input a 3-digit airport code!</em></small>
    </h3>
  </div>
  <div class="overlay"></div>
</header>

<!-- Form -->
  <section class="content-section bg-light" id="form-section">
    <div class="container text-center">
      <div class="row">
        <div class="col-lg-10 mx-auto my-3">
            <%= render 'form', airport: @airport %>
        </div>
      </div>
    </div>
  </section>

<!-- Back -->
<section class="content-section" id="back">
    <div class="container text-center">
        <div class="row">
            <div class="col mx-auto my-3">
                <%= link_to 'Back', airports_path %>
            </div>
        </div>
    </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AirportApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>